-- Dades per a la taula Artista
INSERT INTO Artista (Nom, Cognom, NomArtistic, Datanaix, Foto, Info)
VALUES 
  ('Ramón Luis', 'Ayala Rodriguez', 'Daddy Yankee', '1977-02-03', 'Daddy_yankee.jpg', 'Reggaeton artist'),
  ('Juan', 'Carlos Ozuna', 'Ozuna', '1992-03-13', 'Ozuna.jpg', 'Reggaeton and Latin trap artist'),
  ('Karol', 'G', 'Karol G', '1991-02-14', 'Karol_g.jpg', 'Reggaeton and Latin pop artist'),
  ('J Balvin', 'Balvin', 'J Balvin', '1985-05-07', 'J_balvin.jpg', 'Reggaeton and Latin urban artist'),
  ('Orlando Javier', 'Valle Vega', 'Chencho Corleone', '1979-02-19', 'Chencho_corleone.jpg', 'Reggaeton and Latin urban artist'),
  ('Edwin', 'Vázquez Vega', 'Maldy', '1982-07-29', 'Maldy.jpg', 'Reggaeton and Latin urban artist'),
  ('William Omar', 'Landrón Rivera', 'Don Omar', '1978-02-10', 'Don_omar.jpg', 'Reggaeton and Latin urban artist'),
  ('Benito Antonio', 'Martínez Ocasio', 'Bad Bunny', '1994-3-10', 'Bad_bunny.jpg', 'Reggaeton and Latin pop artist'),
  ('Carlos Efrén', 'Reyes Rosado', 'Farruko', '1991-05-03', 'Farruko.jpg', 'Reggaeton artist'),
  ('Raúl Alejandro', 'Ocasio Ruiz', 'Rauw Alejandro', '1993-01-10', 'Rauw_alejandro.jpg', 'Reggaeton artist'),
  ('Bryan Robert', 'Rohena Pérez', 'Bryant Myers', '1998-04-05', 'Bryant_myers.jpg', 'Reggaeton artist'),
  ('Kevin Manuel', 'Rivera Allende', 'Kevvo', '1998-02-10', 'Kevvo.jpg', 'Reggaeton artist'),
  ('Pedro David', 'Daleccio Torres', 'Dalex', '1990-10-07', 'Dalex.jpg', 'Reggaeton artist'),
  ('Edgardo Rafael', 'Cuevas Feliciano', 'Lyanno', '1995-4-22', 'Lyanno.jpg', 'Reggaeton artist'),
  ('Emmanuel', 'Gazmey Santiago', 'Anuel AA', '1992-11-26', 'Anuel_aa.jpg', 'Reggaeton artist'),
  ('Belcalis', 'Marlenis Almánzar', 'Cardi B', '1992-10-11', 'Cardi_b.jpg', 'Reggaeton artist'),
  ('Manuel', 'Turizo Zapata', 'Manuel Turizo', '2000-04-12', 'Manuel_turizo.jpg', 'Reggaeton artist'),
  ('Michael Anthony', 'Torres Monge', 'Myke Towers', '1994-01-15', 'Myke_towers.jpg', 'Reggaeton artist'),
  ('José Fernando', 'Cosculluela Suárez', 'Cosculluela', '1980-10-15', 'Cardi_b.jpg', 'Reggaeton artist'),
  ('Juan Manuel', 'Magán González', 'Juan Magán', '1978-09-30', 'Cardi_b.jpg', 'Reggaeton and Latin hip hop artist'),
  ('Nick', 'Rivera Caminero', 'Nicky Jam', '1981-03-17', 'Nicky_jam.jpg', 'Reggaeton artist'),
  ('Austin', 'Santos', 'Arcángel', '1938-12-23', 'Arcángel.jpg', 'Reggaeton artist'),
  ('Rebbeca', 'Marie Gomez', 'Becky G', '1997-03-02', 'Becky_g.jpg', 'Reggaeton and Latin pop artist'),
  ('Ibai', 'Llanos', 'Ibai', '1995-04-26', 'Ibai.jpg', 'Idolo');

-- Dades per a la taula Album
INSERT INTO Album (ID_Artista, Titol, DataLlançament, Foto)
VALUES
  (7, 'Meet the Orphans', '2010-11-16', 'Meet the Orphans.jpg'),
  (2, 'X 100PRE', '2018-12-24', 'X 100PRE.jpg'),
  (7, 'iDon', '2009-04-28', 'iDon.jpg'),
  (7, 'The Last Don II', '2018-05-25', 'The Last Don II.jpg'),
  (5, 'Mundial', '2010-04-27', 'Mundial.jpg'),
  (7, 'The Last Don', '2003-01-01', 'The Last Don.jpg'),
  (7, 'Los Bandoleros', '2003-01-01', 'Los Bandoleros.jpg'),
  (6, 'Love AND Sex', '2003-01-01', 'Love AND Sex.jpg'),
  (6, '3MEN2 KBRON', '2003-01-01', '3MEN2 KBRON.jpg'),
  (6, 'Las Que No Iban A Salir', '2003-01-01', 'Las Que No Iban A Salir.jpg'),
  (6, 'Gangalee', '2003-01-01', 'Gangalee.jpg'),
  (6, 'Odisea', '2003-01-01', 'Odisea.jpg'),
  (6, 'House Of Pleasure', '2003-01-01', 'House Of Pleasure.jpg'),
  (6, 'Emmanuel', '2003-01-01', 'Emmanuel.jpg'),
  (6, 'Platonicos', '2003-01-01', 'Platonicos.jpg'),
  (6, 'Aura', '2003-01-01', 'Aura.jpg'),
  (6, 'Blanco Perla', '2003-01-01', 'Blanco Perla.jpg'),
  (6, 'Famouz', '2003-01-01', 'Famouz.jpg'),
  (6, 'Data', '2003-01-01', 'Data.jpg'),
  (6, 'nadie sabe que va a pasar mañana', '2003-01-01', 'nadie sabe que va a pasar mañana.jpg'),
  (6, 'El Principe', '2003-01-01', 'El Principe.jpg'),
  (6, 'El Abayarde', '2003-01-01', 'El Abayarde.jpg'),
  (6, 'Pal Mundo', '2003-01-01', 'Pal Mundo.jpg'),
  (6, 'The King is Back', '2003-01-01', 'The King is Back.jpg'),
  (6, 'Kilates 2', '2003-01-01', 'Kilates 2.jpg'),
  (6, 'Gargolas 3', '2003-01-01', 'Gargolas 3.jpg'),
  (6, 'The Bad Boy', '2003-01-01', 'The Bad Boy.jpg')
  ;

-- Dades per a la taula Genere
INSERT INTO Genere (Nom)
VALUES
  ('Reggaeton'),
  ('Latin Pop'),
  ('Trap'),
  ('Electronic'),
  ('Pop'),
  ('Hip Hop'),
  ('Bachata');

-- Dades per a la taula Canco
INSERT INTO canco (ID_Album, ID_Genere, Titol, Ruta, Img) 
VALUES
  (NULL, 1, 'Amanece', 'Amanece.mp3', 'Amanece.jpg'),
  (NULL, 1, 'Asesina Remix', 'Asesina Remix.mp3', 'Asesina Remix.jpg'),
  (NULL, 1, 'Baila Morena', 'Baila Morena.mp3', 'Baila Morena.jpg'),
  (7, 1, 'Bandoleros', 'Bandoleros.mp3', 'Bandoleros.jpg'),
  (8, 1, 'Candy', 'Candy.mp3', 'Candy.jpg'),
  (9, 3, 'Coco Chanel', 'Coco Chanel.mp3', 'Coco Chanel.jpg'),
  (10, 1, 'CÓMO SE SIENTE Remix', 'CÓMO SE SIENTE Remix.mp3', 'CÓMO SE SIENTE Remix.jpg'),
  (6, 1, 'Dale Don Dale', 'Dale Don Dale.mp3', 'Dale Don Dale.jpg'),
  (1, 1, 'Danza Kuduro', 'Danza Kuduro.mp3', 'Danza Kuduro.jpg'),
  (11, 3, 'Delincuente', 'Delincuente.mp3', 'Delincuente.jpg'),
  (NULL, 1, 'Dembow y Reggaeton', 'Dembow y Reggaeton.mp3', 'Dembow y Reggaeton.jpg'),
  (NULL, 3, 'Diles', 'Diles.mp3', 'Diles.jpg'),
  (3, 1, 'Diva virtual', 'Diva virtual.mp3', 'Diva virtual.jpg'),
  (NULL, 1, 'El Efecto', 'El Efecto.mp3', 'El Efecto.jpg'),
  (12, 3, 'El Farsante', 'El Farsante.mp3', 'El Farsante.jpg'),
  (13, 1, 'Es un secreto', 'Es un secreto.mp3', 'Es un secreto.jpg'),
  (4, 1, 'Guaya Guaya', 'Guaya Guaya.mp3', 'Guaya Guaya.jpg'),
  (14, 1, 'Hasta Que Dios Diga', 'Hasta Que Dios Diga.mp3', 'Hasta Que Dios Diga.jpg'),
  (NULL, 1, 'Hey Mor', 'Hey Mor.mp3', 'Hey Mor.jpg'),
  (NULL, 3, 'Kemba Walker', 'Kemba Walker.mp3', 'Kemba Walker.jpg'),
  (15, 1, 'La Curiosidad', 'La Curiosidad.mp3', 'La Curiosidad.jpg'),
  (5, 1, 'La Despedida', 'La Despedida.mp3', 'La Despedida.jpg'),
  (16, 1, 'La Modelo', 'La Modelo.mp3', 'La Modelo.jpg'),
  (NULL, 1, 'La Nota', 'La Nota.mp3', 'La Nota.jpg'),
  (2, 3, 'LA ROMANA', 'LA ROMANA.mp3', 'LA ROMANA.jpg'),
  (NULL, 1, 'La Rompe Corazones', 'La Rompe Corazones.mp3', 'La Rompe Corazones.jpg'),
  (17, 3, 'Manicomio', 'Manicomio.mp3', 'Manicomio.jpg'),
  (23, 1, 'Mayor Que Yo', 'Mayor Que Yo.mp3', 'Mayor Que Yo.jpg'),
  (18, 3, 'No Me Conoce Remix', 'No Me Conoce Remix.mp3', 'No Me Conoce Remix.jpg'),
  (19, 1, 'PASIEMPRE', 'PASIEMPRE.mp3', 'PASIEMPRE.jpg'),
  (20, 3, 'PERRO NEGRO', 'PERRO NEGRO.mp3', 'PERRO NEGRO.jpg'),
  (21, 1, 'Prrrum', 'Prrrum.mp3', 'Prrrum.jpg'),
  (22, 1, 'Pa Que Retozen', 'Pa Que Retozen.mp3', 'Pa Que Retozen.jpg'),
  (23, 1, 'Rakata', 'Rakata.mp3', 'Rakata.jpg'),
  (NULL, 1, 'Rompe', 'Rompe.mp3', 'Rompe.jpg'),
  (NULL, 1, 'Sábado Rebelde', 'Sábado Rebelde.mp3', 'Sábado Rebelde.jpg'),
  (NULL, 1, 'SANDUNGA', 'SANDUNGA.mp3', 'SANDUNGA.jpg'),
  (12, 3, 'Se Preparo', 'Se Preparo.mp3', 'Se Preparo.jpg'),
  (24, 1, 'Si No Te Quisiera', 'Si No Te Quisiera.mp3', 'Si No Te Quisiera.jpg'),
  (NULL, 1, 'Si Se Da Remix', 'Si Se Da Remix.mp3', 'Si Se Da Remix.jpg'),
  (NULL, 1, 'Si Tu Novio Te Deja Sola', 'Si Tu Novio Te Deja Sola.mp3', 'Si Tu Novio Te Deja Sola.jpg'),
  (NULL, 1, 'Sigueme y Te Sigo', 'Sigueme y Te Sigo.mp3', 'Sigueme y Te Sigo.jpg'),
  (NULL, 3, 'Sola Remix', 'Sola Remix.mp3', 'Sola Remix.jpg'),
  (NULL, 1, 'Travesuras', 'Travesuras.mp3', 'Travesuras.jpg'),
  (12, 3, 'Tu Foto', 'Tu Foto.mp3', 'Tu Foto.jpg'),
  (NULL, 3, 'Tu No Vive Asi', 'Tu No Vive Asi.mp3', 'Tu No Vive Asi.jpg'),
  (NULL, 7,'Tu madre tiene una polla', 'Tu madre tiene una polla.mp3', 'Tu madre tiene una polla.jpg'),
  (NULL, 1, 'Vuelve', 'Vuelve.mp3', 'Vuelve.jpg'),
  (NULL, 1, 'Yandel 150', 'Yandel 150.mp3', 'Yandel 150.jpg'),
  (6, 1, 'Dile', 'Dile.mp3', 'Dile.jpg'),
  (25, 1, 'Yo No Soy Tu Marido', 'Yo No Soy Tu Marido.mp3', 'Yo No Soy Tu Marido.jpg'),
  (26, 1, 'Donde Estan Las Gatas', 'Donde Estan Las Gatas.mp3', 'Donde Estan Las Gatas.jpg'),
  (NULL, 3, 'De Las 2', 'De Las 2.mp3', 'De Las 2.jpg'),
  (26, 1, 'Zun Da Da', 'Zun Da Da.mp3', 'Zun Da Da.jpg');
  
-- Dades per a la taula Crea_musica
INSERT INTO Crea_musica (ID_Canco, ID_Artista)
VALUES
  (1, 15),
  (2, 1),
  (3, 3),
  (4, 7),
  (5, 5),
  (6, 8),
  (7, 8),
  (8, 5),
  (9, 5),
  (10, 5),
  (11, 5),
  (12, 5),
  (13, 5),
  (14, 5),
  (15, 5),
  (16, 5),
  (17, 5),
  (18, 5),
  (19, 5),
  (20, 5),
  (21, 5),
  (22, 5),
  (23, 5),
  (24, 5),
  (25, 5),
  (26, 5),
  (27, 5),
  (28, 5),
  (29, 5),
  (30, 5),
  (31, 5),
  (32, 5),
  (33, 5),
  (34, 5),
  (35, 5),
  (36, 5),
  (37, 5),
  (38, 5),
  (39, 5),
  (40, 5),
  (41, 5),
  (42, 5),
  (43, 5),
  (44, 5),
  (45, 5),
  (46, 5),
  (47, 5),
  (48, 5),
  (49, 5),
  (50, 5),
  (51, 5),
  (52, 5);

-- Dades per a la taula Usuari
INSERT INTO Usuari (Contrasenya, Nom, Email, Cognom, NomUsuari, Foto, Premium)
VALUES
  ('1', 'Maria', 'maria@email.com', 'Gomez', 'user', 'maria.jpg', true),
  ('contrasenya2', 'Pablo', 'pablo@email.com', 'Fernandez', 'pablo_f', 'pablo.jpg', false),
  ('contrasenya3', 'Eva', 'eva@email.com', 'Lopez', 'eva_l', 'eva.jpg', true),
  ('contrasenya4', 'Carlos', 'carlos@email.com', 'Martinez', 'carlos_m', 'carlos.jpg', false),
  ('contrasenya5', 'Laura', 'laura@email.com', 'Rodriguez', 'laura_r', 'laura.jpg', true);

-- Dades per a la taula Llista_Reproduccio
INSERT INTO Llista_Reproduccio (ID_Usuari, Nom)
VALUES
  (1, 'Favorits'),
  (2, 'Reggaeton Mix'),
  (3, 'Latin Hits'),
  (4, 'Top Charts'),
  (5, 'Party Playlist');

-- Dades per a la taula Afegeix
INSERT INTO Afegeix (ID_Canco, ID_LlistaReproduccio)
VALUES
  (1, 1),
  (2, 2),
  (3, 3),
  (4, 4),
  (5, 5);
